//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\icons\\\\default\\\\btnAddEntry.png")]
        public string iconBtnAddEntryLocation {
            get {
                return ((string)(this["iconBtnAddEntryLocation"]));
            }
            set {
                this["iconBtnAddEntryLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\icons\\\\default\\\\btnEdit.png")]
        public string iconBtnEditLocation {
            get {
                return ((string)(this["iconBtnEditLocation"]));
            }
            set {
                this["iconBtnEditLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\icons\\\\default\\\\btnSettings.png")]
        public string iconBtnSettingsLocation {
            get {
                return ((string)(this["iconBtnSettingsLocation"]));
            }
            set {
                this["iconBtnSettingsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\icons\\\\default\\\\btnAddCategory.png")]
        public string iconBtnAddCategoryLocation {
            get {
                return ((string)(this["iconBtnAddCategoryLocation"]));
            }
            set {
                this["iconBtnAddCategoryLocation"] = value;
            }
        }
    }
}
